### ISSUE TITLE
Filenames with slash characters

### ISSUE THREAD

**Issue by tedhuddleston** [sahilchaddha/node-rtsp-recorder#1]
Hi, I am having an issue when doing image or video capture from homebridge-dafang where the filenames are created with slash characters in them - for example 2018-12-01T21/21/27-06/00.jpg - it appears the time stamp is getting created with slashes instead of colons? see this reddit post:

https://www.reddit.com/r/homebridge/comments/a271bo/homebridgedafang_image_capture/

Is this something that you can take a look at? I would like to have the capture files sync up with OneDrive, but it does not like these file names.

**Comment by sahilchaddha** [comment]
Hey @tedhuddleston ,

Currently the directory date format is `MMM-Do-YY`
And filename format is `2014-09-08T08:02:17-05:00.[extension]`

Unfortunately the system replaces `:` to `/` in filename and saves the file in format `2014-09-08T08/02:/17-05/00.[extension]`

I will be updating default filename format to `YYYY-M-D-h-mm-ss` i.e. `2014-9-8-12-00-00`. Will this format work for you ?

I will update `node-rtsp-recorder` as well as `homebridge-dafang` for users to custom define their Directory Name & filename from config.json.

For E.g. : 
```json
             {...}
             {
                "cameraName": "My Dafang",
                "cameraRTSPStreamUrl": "rtsp://192.168.1.12:8554/unicast",
                "mqttTopic": "myhome/dafang/#",
                "folder": "/Users/sahilchaddha/Sahil/Recordings/",
                "recordingDirectoryPathFormat": "MMM-Do-YYYY", // Directory Path Format moment.js
                "recordingFilenameFormat": "M_D_YYYY_ h_mm_ss_a", // Filename Format moment.js
                "accessories": [
              {...} 
```
Default DirectoryPath : `MMM-Do-YY`
Default Filename : `YYYY-M-D-h-mm-ss`

Refer to https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/ for custom formats.

Do note each filename must be unique inside the recording folder, hence seconds are important to keep filenames unique.

I will soon be updating the npm packages with this fix. Will update here once done.

**Comment by sahilchaddha** [comment]
Hey @tedhuddleston , You can upgrade `homebridge-dafang` to 1.4.3
The plugin is updated to new default filenames & directoryPaths. Also you can set custom format for DirectoryPath & FileName. Refer to https://github.com/sahilchaddha/homebridge-dafang#camera-config-
